export default {
  'common.form.validation.failed':'خطا در اطلاعات ورودی',
  'invalid.authorization.code':'کد وارد شده نامعتبر است.',
  'bad.credential':'نام کاربری یا رمز ورود نامعتبر است.',
  'username.not.found':'نام کاربری نامعتبر است.',
  'order.submition.exception':'خطا در ثبت سفارش',
  'unknown.exception':'خطا در سرور',
  'common.form.required.error':'فیلد های اجباری را تکمیل نمایید.',
  'server.connection.failed':'خطا در ارتباط با سرور',
  'pass.confirm.not.matched':'رمز عبور با تکرار آن یکسان نیست.',
  'pass.min.length.violated':'رمز عبور شما باید حداقل از 6 کاراکتر تشکیل شده باشد.',
  'invalid.input.data':'خطا در داده ورودی',
  'user.inactive':'حساب کاربری شما غیرفعال می باشد.',
  'user.expired':'حساب کاربری شما منقضی شده است.',
}
