//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.02 at 08:59:53 PM IRST 
//


package com.mata.webservice.sms;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mata.webservice.sms package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mata.webservice.sms
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Getsystemcredit }
     * 
     */
    public Getsystemcredit createGetsystemcredit() {
        return new Getsystemcredit();
    }

    /**
     * Create an instance of {@link GetsystemcreditResponse }
     * 
     */
    public GetsystemcreditResponse createGetsystemcreditResponse() {
        return new GetsystemcreditResponse();
    }

    /**
     * Create an instance of {@link MultiSMSEngine }
     * 
     */
    public MultiSMSEngine createMultiSMSEngine() {
        return new MultiSMSEngine();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link MultiSMSEngineResponse }
     * 
     */
    public MultiSMSEngineResponse createMultiSMSEngineResponse() {
        return new MultiSMSEngineResponse();
    }

    /**
     * Create an instance of {@link MultiSMSEngineBlackList }
     * 
     */
    public MultiSMSEngineBlackList createMultiSMSEngineBlackList() {
        return new MultiSMSEngineBlackList();
    }

    /**
     * Create an instance of {@link MultiSMSEngineBlackListResponse }
     * 
     */
    public MultiSMSEngineBlackListResponse createMultiSMSEngineBlackListResponse() {
        return new MultiSMSEngineBlackListResponse();
    }

    /**
     * Create an instance of {@link MultiSMSEngine021 }
     * 
     */
    public MultiSMSEngine021 createMultiSMSEngine021() {
        return new MultiSMSEngine021();
    }

    /**
     * Create an instance of {@link MultiSMSEngine021Response }
     * 
     */
    public MultiSMSEngine021Response createMultiSMSEngine021Response() {
        return new MultiSMSEngine021Response();
    }

    /**
     * Create an instance of {@link GetStatusSMSEngine }
     * 
     */
    public GetStatusSMSEngine createGetStatusSMSEngine() {
        return new GetStatusSMSEngine();
    }

    /**
     * Create an instance of {@link GetStatusSMSEngineResponse }
     * 
     */
    public GetStatusSMSEngineResponse createGetStatusSMSEngineResponse() {
        return new GetStatusSMSEngineResponse();
    }

    /**
     * Create an instance of {@link SingleSMSEngine }
     * 
     */
    public SingleSMSEngine createSingleSMSEngine() {
        return new SingleSMSEngine();
    }

    /**
     * Create an instance of {@link SingleSMSEngineResponse }
     * 
     */
    public SingleSMSEngineResponse createSingleSMSEngineResponse() {
        return new SingleSMSEngineResponse();
    }

    /**
     * Create an instance of {@link SingleSMSEngineBlacklist }
     * 
     */
    public SingleSMSEngineBlacklist createSingleSMSEngineBlacklist() {
        return new SingleSMSEngineBlacklist();
    }

    /**
     * Create an instance of {@link SingleSMSEngineBlacklistResponse }
     * 
     */
    public SingleSMSEngineBlacklistResponse createSingleSMSEngineBlacklistResponse() {
        return new SingleSMSEngineBlacklistResponse();
    }

    /**
     * Create an instance of {@link SingleSMSEngine021 }
     * 
     */
    public SingleSMSEngine021 createSingleSMSEngine021() {
        return new SingleSMSEngine021();
    }

    /**
     * Create an instance of {@link SingleSMSEngine021Response }
     * 
     */
    public SingleSMSEngine021Response createSingleSMSEngine021Response() {
        return new SingleSMSEngine021Response();
    }

}
