//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.02 at 08:59:53 PM IRST 
//


package com.mata.webservice.sms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SingleSMSEngineBlacklistResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "singleSMSEngineBlacklistResult"
})
@XmlRootElement(name = "SingleSMSEngineBlacklistResponse")
public class SingleSMSEngineBlacklistResponse {

    @XmlElement(name = "SingleSMSEngineBlacklistResult")
    protected String singleSMSEngineBlacklistResult;

    /**
     * Gets the value of the singleSMSEngineBlacklistResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSingleSMSEngineBlacklistResult() {
        return singleSMSEngineBlacklistResult;
    }

    /**
     * Sets the value of the singleSMSEngineBlacklistResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSingleSMSEngineBlacklistResult(String value) {
        this.singleSMSEngineBlacklistResult = value;
    }

}
